@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Histoire4{
+{static}  main() : (java.lang.String[])void

}
class Cowboy{
- gains : int
- captures : java.util.Set<western.HorsLaLoi>
-{static}  boissonParDefaut : western.Boisson
+ getPseudo() : ()java.lang.String

+ liberer() : (western.Dame)void

+ liberer() : (java.util.List<western.Dame>)void

+ capturer() : (western.HorsLaLoi)void

+ tirerSur() : (western.HorsLaLoi)void

+ sePresenter() : ()void

+{static}  getBoissonParDefaut() : ()western.Boisson

+{static}  setBoissonParDefaut() : (western.Boisson)void

}
class Substantif{
- nom : java.lang.String
- genre : western.Genre
+ getNom() : ()java.lang.String

+ getGenre() : ()western.Genre

+ toString() : ()java.lang.String

+{static}  isVowel() : (char)boolean

+{static}  startsWithVowel() : (java.lang.String)boolean

+ getArticleIndefini() : ()java.lang.String

+ avecArticleIndefini() : ()java.lang.String

+{static}  getArticleDefini() : (western.Genre)java.lang.String

+ getArticleDefini() : ()java.lang.String

+ avecArticleDefini() : ()java.lang.String

+{static}  faireElision() : (java.lang.String)java.lang.String

+ elision() : ()boolean

+ getArticlePartitif() : ()java.lang.String

+ avecArticlePartitif() : ()java.lang.String

+ avecElision() : (java.lang.String)java.lang.String

+ avecPreposition() : (java.lang.String)java.lang.String

}
class Narrateur{
+ dire() : (java.lang.String)void

+ boire() : (western.Boisson)void

+ boire() : ()void

+ getPseudo() : ()java.lang.String

}
class Boisson{
- substantif : western.Substantif
+{static}  EAU : western.Boisson
+ getNom() : ()java.lang.String

+ getGenre() : ()western.Genre

+ getNomAvecArticleIndefini() : ()java.lang.String

+ getNomAvecArticlePartitif() : ()java.lang.String

+ getNomAvecArticleDefini() : ()java.lang.String

+ getNomAvecPreposition() : (java.lang.String)java.lang.String

}
class Brigand{
#{static}  LOOK_PAR_DEFAUT : java.lang.String
- look : java.lang.String
- recompense : int
- estLibre : boolean
- captives : java.util.List<western.Dame>
- gardien : western.Cowboy
-{static}  boissonParDefaut : western.Boisson
+ getLook() : ()java.lang.String

+ getRecompense() : ()int

+ estLibre() : ()boolean

+ kidnapper() : (western.Dame)void

+ seFaireCapturer() : (western.Cowboy)void

+ seFaireTirerDessus() : (western.Cowboy)void

+ getPseudo() : ()java.lang.String

+ getCaptives() : ()java.util.List<western.Dame>

+ sePresenter() : ()void

+{static}  getBoissonParDefaut() : ()western.Boisson

+{static}  setBoissonParDefaut() : (western.Boisson)void

}
class Personnage{
-{static}  BOISSON_PAR_DEFAUT : western.Boisson
- nom : java.lang.String
- boisson : western.Boisson
+ dire() : (java.lang.String)void

+ sePresenter() : ()void

+ boire() : (western.Boisson)void

+ boire() : ()void

+ getNom() : ()java.lang.String

+ getBoisson() : ()western.Boisson

+{static}  getPseudos() : (java.util.List<? extends western.Nommable>)java.lang.String

+{static}  getBoissonParDefaut() : ()western.Boisson

}
class Dame{
- estLibre : boolean
- sauveur : western.Cowboy
- ravisseur : western.HorsLaLoi
-{static}  boissonParDefaut : western.Boisson
+ getPseudo() : ()java.lang.String

+ seFaireKidnapper() : (western.HorsLaLoi)void

+ seFaireLiberer() : (western.Cowboy)void

+ estLibre() : ()boolean

+ sePresenter() : ()void

+{static}  getBoissonParDefaut() : ()western.Boisson

+{static}  setBoissonParDefaut() : (western.Boisson)void

+ getRavisseur() : ()western.HorsLaLoi

}
class Ripou{
- brigand : western.Brigand
+ getLook() : ()java.lang.String

+ estLibre() : ()boolean

+ getRecompense() : ()int

+ kidnapper() : (western.Dame)void

+ getCaptives() : ()java.util.List<western.Dame>

+ seFaireCapturer() : (western.Cowboy)void

+ seFaireTirerDessus() : (western.Cowboy)void

+ getPseudo() : ()java.lang.String

+ sePresenter() : ()void

+ liberer() : (western.Dame)void

}
interface HorsLaLoi<<interface>>{
+ estLibre() : ()boolean

+ getRecompense() : ()int

+ kidnapper() : (western.Dame)void

+ seFaireCapturer() : (western.Cowboy)void

+ seFaireTirerDessus() : (western.Cowboy)void

+ getLook() : ()java.lang.String

+ getCaptives() : ()java.util.List<western.Dame>

}
interface Nommable<<interface>>{
+ getNom() : ()java.lang.String

+ getPseudo() : ()java.lang.String

}
enum Genre<<Enum>>{
}

@enduml