@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml

participant Java2puml as J
participant ToolProvider.Class as T
participant toolProvider as t
participant FirstDoclet as F

[->J ++

J -> T ++: toolProvider = findFirst("javadoc")
return Optionnal<ToolProvider> : toolProvider
create t
J -> t ++: get()
return toolProvider

J -> t ++: getName()
return name = getName()
J -> t ++ : run(System.out, System.err, args)
t -->> F ** : <<Create>> FirstDoclet
return
@enduml