@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

enum Genre<<enum>> {}
class Histoire4{}
class Cowboy{}
class Substantif{}
interface HorsLaLoi<<interface>> {}
interface Nommable<<interface>> {}
class Narrateur{}
class Boisson{}
class Brigand{}
class Personnage{}
class Dame{}
class Ripou{}
@enduml