@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class western.Histoire4 {
	+<<Create>> Histoire4()
	+ main(args : String[])
}

class western.Cowboy {
	+<<Create>> Cowboy(nom : String)
	+<<Create>> Cowboy(boisson : Boisson, boisson : Boisson, )
	+ getPseudo() : String
	+ liberer(dame : Dame)
	+ liberer(captives : Dame[*])
	+ capturer(horsLaLoi : HorsLaLoi)
	+ tirerSur(brigand : HorsLaLoi)
	+ sePresenter()
	+ getBoissonParDefaut() : Boisson
	+ setBoissonParDefaut(boisson : Boisson)
}

class western.Substantif {
	+<<Create>> Substantif(genre : Genre, genre : Genre, )
	+ getNom() : String
	+ getGenre() : Genre
	+ toString() : String
	+ isVowel(c : char) : Boolean
	+ startsWithVowel(s : String) : Boolean
	+ getArticleIndefini() : String
	+ avecArticleIndefini() : String
	+ getArticleDefini(genre : Genre) : String
	+ getArticleDefini() : String
	+ avecArticleDefini() : String
	+ faireElision(article : String) : String
	+ elision() : Boolean
	+ getArticlePartitif() : String
	+ avecArticlePartitif() : String
	+ avecElision(article : String) : String
	+ avecPreposition(preposition : String) : String
}

class western.Narrateur {
	+<<Create>> Narrateur()
	+<<Create>> Narrateur(nom : String)
	+ dire(texte : String)
	+ boire(boisson : Boisson)
	+ boire()
	+ getPseudo() : String
}

class western.Boisson {
	+<<Create>> Boisson(genre : Genre, genre : Genre, )
	+ getNom() : String
	+ getGenre() : Genre
	+ getNomAvecArticleIndefini() : String
	+ getNomAvecArticlePartitif() : String
	+ getNomAvecArticleDefini() : String
	+ getNomAvecPreposition(preposition : String) : String
}

class western.Brigand {
	+<<Create>> Brigand(nom : String)
	+<<Create>> Brigand(boisson : Boisson, boisson : Boisson, )
	+<<Create>> Brigand(look : String, look : String, look : String, )
	+ getLook() : String
	+ getRecompense() : Integer
	+ estLibre() : Boolean
	+ kidnapper(dame : Dame)
	+ seFaireCapturer(cowBoy : Cowboy)
	+ seFaireTirerDessus(cowBoy : Cowboy)
	+ getPseudo() : String
	+ getCaptives() : Dame[*]
	+ sePresenter()
	+ getBoissonParDefaut() : Boisson
	+ setBoissonParDefaut(boisson : Boisson)
}

class western.Personnage {
	+<<Create>> Personnage(nom : String)
	+<<Create>> Personnage(boisson : Boisson, boisson : Boisson, )
	+ dire(texte : String)
	+ sePresenter()
	+ boire(boisson : Boisson)
	+ boire()
	+ getNom() : String
	+ getBoisson() : Boisson
	+ getPseudos(personnages : Nommable[*]) : String
	+ getBoissonParDefaut() : Boisson
}

class western.Dame {
	+<<Create>> Dame(nom : String)
	+<<Create>> Dame(boisson : Boisson, boisson : Boisson, )
	+ getPseudo() : String
	+ seFaireKidnapper(horsLaLoi : HorsLaLoi)
	+ seFaireLiberer(cowBoy : Cowboy)
	+ estLibre() : Boolean
	+ sePresenter()
	+ getBoissonParDefaut() : Boisson
	+ setBoissonParDefaut(boisson : Boisson)
	+ getRavisseur() : HorsLaLoi
}

class western.Ripou {
	+<<Create>> Ripou(nom : String)
	+<<Create>> Ripou(boisson : Boisson, boisson : Boisson, )
	+<<Create>> Ripou(look : String, look : String, look : String, )
	+ getLook() : String
	+ estLibre() : Boolean
	+ getRecompense() : Integer
	+ kidnapper(dame : Dame)
	+ getCaptives() : Dame[*]
	+ seFaireCapturer(cowBoy : Cowboy)
	+ seFaireTirerDessus(cowBoy : Cowboy)
	+ getPseudo() : String
	+ sePresenter()
	+ liberer(dame : Dame)
}

interface western.HorsLaLoi<<interface>> {
	+ estLibre() : Boolean
	+ getRecompense() : Integer
	+ kidnapper(dame : Dame)
	+ seFaireCapturer(cowBoy : Cowboy)
	+ seFaireTirerDessus(cowBoy : Cowboy)
	+ getLook() : String
	+ getCaptives() : Dame[*]
}

interface western.Nommable<<interface>> {
	+ getNom() : String
	+ getPseudo() : String
}

enum western.Genre<<enumeration>> {
	FEMININ
	MASCULIN
}


western.Personnage<|--western.Cowboy
western.HorsLaLoi" [*] \n captures"<--* western.Cowboy
western.Boisson" 1 \nboissonParDefaut"<--* western.Cowboy

java.lang.String" 1 \nnom"<--* western.Substantif
western.Genre" 1 \ngenre"<--* western.Substantif

western.Personnage<|--western.Narrateur

western.Substantif" 1 \nsubstantif"<--* western.Boisson
western.Boisson" 1 \nEAU"<--* western.Boisson

western.Personnage<|--western.Brigand
western.HorsLaLoi<|..western.Brigand
java.lang.String" 1 \nLOOK_PAR_DEFAUT"<--* western.Brigand
java.lang.String" 1 \nlook"<--* western.Brigand
western.Dame" [*] \n captives"<--* western.Brigand
western.Cowboy" 1 \ngardien"<--* western.Brigand
western.Boisson" 1 \nboissonParDefaut"<--* western.Brigand

western.Nommable<|..western.Personnage
western.Boisson" 1 \nBOISSON_PAR_DEFAUT"<--* western.Personnage
java.lang.String" 1 \nnom"<--* western.Personnage
western.Boisson" 1 \nboisson"<--* western.Personnage

western.Personnage<|--western.Dame
western.Cowboy" 1 \nsauveur"<--* western.Dame
western.HorsLaLoi" 1 \nravisseur"<--* western.Dame
western.Boisson" 1 \nboissonParDefaut"<--* western.Dame

western.Cowboy<|--western.Ripou
western.HorsLaLoi<|..western.Ripou
western.Brigand" 1 \nbrigand"<--* western.Ripou




@enduml