@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml

participant Java2puml as J
participant ToolProvider.Class as T
participant ":Optionnal<ToolProvider>" as tp
participant "toolProvider:ToolProvider" as t
participant FirstDoclet as F


[->J ++


J -> T ++: toolProvider = findFirst("javadoc")
create tp
T -> tp: <<Create>>
return Optionnal<ToolProvider>
J -> tp ++: get()
create t
tp -> t: <<Create>>
return toolProvider: ToolProvider

J -> t ++: getName()
return name = getName()
J -> t ++ : run(System.out, System.err, args)
t -->> F ** : <<Create>> FirstDoclet
return
@enduml